"""add conversation version

Revision ID: 0ca9289dc3ad
Revises: dbcca5c61cb1
Create Date: 2026-08-06 07:23:02.554955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca9289dc3ad'
down_revision: Union[str, Sequence[str], None] = 'dbcca5c61cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "version",
            sa.Integer(),
            server_default="1",
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_conversations_version_positive",
        "conversations",
        "version >= 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_conversations_version_positive",
        "conversations",
        type_="check",
    )
    op.drop_column("conversations", "version")
    # ### end Alembic commands ###
