"""create organizations table

Revision ID: 434f9f607e72
Revises: 9eeab0397832
Create Date: 2026-07-30 23:12:52.106664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434f9f607e72'
down_revision: Union[str, Sequence[str], None] = '9eeab0397832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.CheckConstraint("slug = lower(slug) AND slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='ck_organizations_slug_valid'),
    sa.CheckConstraint('name = btrim(name) AND char_length(name) >= 1', name='ck_organizations_name_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_organizations_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
