"""create outbox messages table

Revision ID: 6e8d6c0665cd
Revises: 885dbeef2e5f
Create Date: 2026-08-11 11:57:19.362770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8d6c0665cd'
down_revision: Union[str, Sequence[str], None] = '885dbeef2e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_name = btrim(task_name) AND char_length(task_name) BETWEEN 1 AND 255', name='ck_outbox_messages_task_name_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_messages_published_at_created_at_id', 'outbox_messages', ['published_at', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_messages_published_at_created_at_id', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
