"""create conversations and messages

Revision ID: 74909fb30ff4
Revises: d6e4b77ac3a3
Create Date: 2026-08-03 12:45:12.304576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74909fb30ff4'
down_revision: Union[str, Sequence[str], None] = 'd6e4b77ac3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', name='conversation_status', native_enum=False, length=20), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'PENDING', 'RESOLVED')", name='ck_conversations_status_valid'),
    sa.CheckConstraint('subject = btrim(subject) AND char_length(subject) BETWEEN 1 AND 200', name='ck_conversations_subject_valid'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_conversations_created_by_user_id_users', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_conversations_organization_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_organization_created_at_id', 'conversations', ['organization_id', 'created_at', 'id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('sender_type', sa.Enum('USER', 'AGENT', 'AI', 'SYSTEM', name='message_sender_type', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(sender_type IN ('USER', 'AGENT') AND author_id IS NOT NULL) OR (sender_type IN ('AI', 'SYSTEM') AND author_id IS NULL)", name='ck_messages_sender_author_valid'),
    sa.CheckConstraint("sender_type IN ('USER', 'AGENT', 'AI', 'SYSTEM')", name='ck_messages_sender_type_valid'),
    sa.CheckConstraint('content = btrim(content) AND char_length(content) BETWEEN 1 AND 10000', name='ck_messages_content_valid'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_messages_author_id_users', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_messages_conversation_id_conversations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created_at_id', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created_at_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_organization_created_at_id', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
