"""create documents table

Revision ID: 885dbeef2e5f
Revises: e490ea5d4643
Create Date: 2026-08-09 10:08:17.801709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885dbeef2e5f'
down_revision: Union[str, Sequence[str], None] = 'e490ea5d4643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status', native_enum=False, length=20), server_default='PENDING', nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name='ck_documents_status_valid'),
    sa.CheckConstraint('content_type = lower(btrim(content_type)) AND char_length(content_type) BETWEEN 1 AND 255', name='ck_documents_content_type_valid'),
    sa.CheckConstraint('error_message IS NULL OR (error_message = btrim(error_message) AND char_length(error_message) BETWEEN 1 AND 1000)', name='ck_documents_error_message_valid'),
    sa.CheckConstraint('original_filename = btrim(original_filename) AND char_length(original_filename) BETWEEN 1 AND 255', name='ck_documents_original_filename_valid'),
    sa.CheckConstraint('storage_key = btrim(storage_key) AND char_length(storage_key) BETWEEN 1 AND 512', name='ck_documents_storage_key_valid'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_documents_organization_id_organizations', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name='fk_documents_uploaded_by_user_id_users', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key', name='uq_documents_storage_key')
    )
    op.create_index('ix_documents_organization_created_at_id', 'documents', ['organization_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_documents_status_processing_started_at', 'documents', ['status', 'processing_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_status_processing_started_at', table_name='documents')
    op.drop_index('ix_documents_organization_created_at_id', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
