"""create users table

Revision ID: 8ecbfa06717e
Revises: 
Create Date: 2026-07-30 04:26:51.705253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecbfa06717e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.CheckConstraint('name = btrim(name) AND char_length(name) >= 1', name='ck_users_name_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_ci', 'users', [sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_ci', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
