"""add organization members user lookup index

Revision ID: d6e4b77ac3a3
Revises: d415e08e36cf
Create Date: 2026-08-01 03:32:44.873826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e4b77ac3a3'
down_revision: Union[str, Sequence[str], None] = 'd415e08e36cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_organization_members_user_id_organization_id', 'organization_members', ['user_id', 'organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_members_user_id_organization_id', table_name='organization_members')
    # ### end Alembic commands ###
