"""add organization member roles

Revision ID: dbcca5c61cb1
Revises: c8e5ed21a004
Create Date: 2026-08-05 05:52:45.592520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcca5c61cb1'
down_revision: Union[str, Sequence[str], None] = 'c8e5ed21a004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_members",
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "AGENT",
                name="organization_role",
                native_enum=False,
                length=20,
            ),
            server_default="AGENT",
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_organization_members_role_valid",
        "organization_members",
        "role IN ('OWNER', 'ADMIN', 'AGENT')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_organization_members_role_valid",
        "organization_members",
        type_="check",
    )
    op.drop_column("organization_members", "role")
    # ### end Alembic commands ###
