"""add document chunks

Revision ID: ed6e42cfda0d
Revises: d84954237584
Create Date: 2026-08-14 11:32:26.806976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6e42cfda0d'
down_revision: Union[str, Sequence[str], None] = 'd84954237584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('index_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name='ck_document_chunks_content_hash_valid'),
    sa.CheckConstraint('(page_start IS NULL AND page_end IS NULL) OR (page_start IS NOT NULL AND page_end IS NOT NULL AND page_start <= page_end)', name='ck_document_chunks_page_range_valid'),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunks_chunk_index_nonnegative'),
    sa.CheckConstraint('content = btrim(content) AND char_length(content) >= 1', name='ck_document_chunks_content_valid'),
    sa.CheckConstraint('index_version = btrim(index_version) AND char_length(index_version) BETWEEN 1 AND 64', name='ck_document_chunks_index_version_valid'),
    sa.CheckConstraint('page_end IS NULL OR page_end >= 1', name='ck_document_chunks_page_end_valid'),
    sa.CheckConstraint('page_start IS NULL OR page_start >= 1', name='ck_document_chunks_page_start_valid'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_document_chunks_document_id_documents', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_document_chunks_organization_id_organizations', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', 'index_version', name='uq_document_chunks_document_index_version')
    )
    op.create_index('ix_document_chunks_organization_document', 'document_chunks', ['organization_id', 'document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_organization_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
